version: '3.4'

networks:
  rabbitmqnetwork:
    external:
      name: rabbitmqnetwork  

services:
  consumer:
    image: ${DOCKER_REGISTRY-}consumer
    build:
      context: .
      dockerfile: Consumer/Dockerfile
    networks:
      - rabbitmqnetwork   

  producer:
    image: ${DOCKER_REGISTRY-}producer
    build:
      context: .
      dockerfile: Producer/Dockerfile
    networks:
      - rabbitmqnetwork
    depends_on:
      - consumer   
      - aspconsumer


  aspconsumer:
    image: ${DOCKER_REGISTRY-}aspconsumer
    build:
      context: .
      dockerfile: ASPConsumer/Dockerfile
    networks:
      - rabbitmqnetwork

